### ISSUE TITLE
这个发布文章

### ISSUE THREAD

**Issue by ghost** [xland/xiangxuema#1]
为啥不是用对方api直接发，而是浏览器的形式

**Comment by xland** [comment]
@mufengcoding 
因为对方没有提供相应的API啊

**Comment by ghost** [comment]
数据是以什么形式保存的呀

**Comment by xland** [comment]
@mufengcoding 

大部分数据是以JSON的形式分多个文件保存在客户端本地的

**Comment by raysico** [comment]
> @mufengcoding
> 
> 大部分数据是以JSON的形式分多个文件保存在客户端本地的

同问，分布多个文件保存在本地的哪个地方？可以指定保存的地址吗？

**Comment by xland** [comment]
@raysico 
目前还不能指定保存路径，不过可以考虑以后允许用户指定。

mac上的路径：/Users/[your name]/Library/Application Support/[app name]/Default/xxm
win上的路径类似
