### ISSUE TITLE
带图文本无法上传至简书

### ISSUE THREAD

**Issue by jrenzone** [xland/xiangxuema#10]
测试了一下,单纯的文本上传没什么问题,本来写了一个推广分享这个软件的小文章,结果因为有图,等待了很久也无法上传,所以过来提个issue,望改进.加油

**Comment by xland** [comment]
@Jayren77 
我去测测！

眼含泪水！心怀感激！

**Comment by xland** [comment]
@Jayren77 ,我试过了，图片传到简书，在我这里是没问题得。
你那边出问题可能有两个原因，

1：如果这是一篇全新的文章，APP给你打开简书文章编辑页面之后，你要点一下“新建文章”才行；
2：我刚刚发布了一个版本，不知道你用的是不是最新的版本，APP右下角可以看到版本号；

文章发布后，文章链接这里留一下，我去点个赞

**Comment by jrenzone** [comment]
已更新到6.0.7

**Comment by jrenzone** [comment]
![image](https://user-images.githubusercontent.com/20200071/53245661-48e8b180-36e9-11e9-8a6e-299071d40c5e.png)点击新建后,这里大概需要等待多久呢?还是直接就会有结果?
![image](https://user-images.githubusercontent.com/20200071/53245716-6f0e5180-36e9-11e9-92bc-d74fb0659e3a.png)

**Comment by xland** [comment]
我这里非常快的就会有结果，简书用的7牛的云存储，速度还可以的，我明天再看看
@Jayren77

**Comment by xland** [comment]
@Jayren77 

已解决这个问题，并发布了新版本
请更新一下新版本，再看一下
谢谢

**Comment by jrenzone** [comment]
https://www.jianshu.com/p/353953e0e4e9
已经愉快的提交.感谢

**Comment by xland** [comment]
@Jayren77 
给你赞赏了两颗糖 ^_^
