### ISSUE TITLE
有计划支出Markdown 编辑器吗？ 

### ISSUE THREAD

**Issue by lfzm** [xland/xiangxuema#11]

**Comment by xland** [comment]
@AClumsy 
有这个计划，最近在思考怎么做

**Comment by lfzm** [comment]
期待期待，如果可以打通Github进行云存储那就更加完美了

**Comment by lfzm** [comment]
@xland 你可以去看一下有道云的文档实现，做二个文件类型，因为很多博客不支持Markdown

**Comment by xland** [comment]
@AClumsy 
嗯，肯定要考虑这些

**Comment by xland** [comment]
已支持markdown，请升级新版本
