### ISSUE TITLE
删除标签后未更新数据结果

### ISSUE THREAD

**Issue by huangwenxiang** [xland/xiangxuema#15]
删除标签后未更新数据结果

**Comment by xland** [comment]
@huangwenxiang 
我刚试了一下，MAC上没问题呀，
你是什么系统？能告诉我具体重现这个BUG的步骤吗？

**Comment by huangwenxiang** [comment]
MAC 版本。
![image](https://user-images.githubusercontent.com/5449377/53620355-9e631800-3c2d-11e9-8257-da38870126d2.png)
![image](https://user-images.githubusercontent.com/5449377/53620362-a58a2600-3c2d-11e9-8fe0-22cf39cd5904.png)
![image](https://user-images.githubusercontent.com/5449377/53620367-a7ec8000-3c2d-11e9-99a1-dbecd442722f.png)

**Comment by xland** [comment]
哈！我待会儿看看！谢谢！

**Comment by xland** [comment]
@huangwenxiang 
新版本已解决此问题，暂时先关掉issue啦~~~
