### ISSUE TITLE
微信不行呢

### ISSUE THREAD

**Issue by mzy666888** [xland/xiangxuema#17]
写的文章，微信公众号抓不到呀

**Comment by xland** [comment]
@mzy666888 请问什么系统？APP版本号？

**Comment by mzy666888** [comment]
Windows端，
![image](https://user-images.githubusercontent.com/2587129/53674263-aff8fe00-3cc7-11e9-94c3-aef87bf98a7b.png)
这里面是空的呢

![image](https://user-images.githubusercontent.com/2587129/53674330-2ac21900-3cc8-11e9-8332-8ca9329a205a.png)

**Comment by xland** [comment]
收到！待会儿我试试

**Comment by xland** [comment]
@mzy666888 

新版本再微信下已验证，没有问题了，暂时先关掉此issue了

**Comment by zhangferry** [comment]
如果是简短的测试内容可以识别，如果是之前的文章直接粘贴过来的识别不了

**Comment by xland** [comment]
@zhangferry ，我再试试，能把你黏贴的文章的地址发给我吗？

**Comment by zhangferry** [comment]
@xland 感谢回复。https://github.com/zhangferry/iOSMonthlyReport/blob/master/iOS%E5%BC%80%E5%8F%91%E6%9C%88%E6%8A%A5%2313%7C201907.md 这个是源地址，markdown格式

**Comment by xland** [comment]
@zhangferry 

我手动拷贝这篇文章，并黏贴到“想学吗”HTML编辑器里，提交的公众号平台上，在我这里是没问题的，
（文章图片较大，上传确实有点慢）
![image](https://user-images.githubusercontent.com/2980915/63314071-20a8db00-c339-11e9-9c93-4b34631d311c.png)

请问你是怎么操作的？尽量详细，以便我重现问题

**Comment by zhangferry** [comment]
@xland 我之前是添加的markdown格式，无法识别。当我把文章中的图片删除之后就可以识别了。但是识别的内容不是markdown渲染出的效果而是纯文本。

我试了用html格式，能识别，但也是纯文本。不知道楼主是怎么操作的，可以识别表格和超链接格式。自动生成的还是需要别的操作。

目前看来是有两个问题：
1、markdown格式图片无法识别
2、markdown渲染格式无法同步

**Comment by xland** [comment]
@zhangferry 

我的操作步骤如下：
打开你上面发的链接，鼠标选择，复制；
打开“想学吗”，创建HTML格式的知识，黏贴，
点“想学吗”的发布按钮，发表到微信公众号，稍等一会儿，文章进入公众号编辑器；
（你把HTML代码黏贴到编辑器的源码模式下，也没问题的）
（你也可以使用我提供的“想学吗”浏览器插件，来采集你的文章）

markdown格式的，我待会儿试试。
