### ISSUE TITLE
建议支持MarkDown并降低简书的优先级

### ISSUE THREAD

**Issue by sisyphsu** [xland/xiangxuema#19]
许多开发人员都直接使用MarkDown撰写笔记文章，并且它也是标准的文档语言。
不要担心某些平台不支持MarkDown，有许多库可以直接将MarkDown转换为html，与富文本编辑器的最终输出差不多。

平台支持上建议支持GitHub，而`简书`可以放在最后，甚至直接删掉它。

现在还有多少开发人员还在使用`简书`呢？

大家不要忘记了，当年简书CEO与其签约作者&好朋友对程序员群体的疯狂嘲讽与辱骂攻击，甚至利用官方权限封杀不堪受辱而反击的程序员。

既然简书官方对待程序员如此刻薄，还有必要对接它、宣传它吗？

**Comment by xland** [comment]
@sisyphsu 
嗯！markdown的支持工作已经提上日程了！

**Comment by xland** [comment]
已支持markdown，请升级新版本
