### ISSUE TITLE
【偶发】简书部分图片上传不成功

### ISSUE THREAD

**Issue by ajeyone** [xland/xiangxuema#23]
我写了一篇文章，里面有一些列表和一些通过剪贴板粘贴进去的图片。
简书上传不了，我试过几个字的文章带个图也都可以，就我写那个稍微大一点的不可以。
后来再看图片丢了！！丢了两张图！！
![image](https://user-images.githubusercontent.com/3040492/54016933-7b051380-41bf-11e9-89dc-ca8deccc36d6.png)

**Comment by xland** [comment]
收到！我马上检查一下代码，看看什么地方会导致这类问题！

**Comment by xland** [comment]
@ajeyone ，软件右下角有版本号，你能告诉我你用的软件的版本号吗

**Comment by xland** [comment]
@ajeyone 上传不成功的图片是不是特别大？

**Comment by ajeyone** [comment]
> @ajeyone ，软件右下角有版本号，你能告诉我你用的软件的版本号吗

最新的6.1.2

**Comment by ajeyone** [comment]
> @ajeyone 上传不成功的图片是不是特别大？

不大，QQ截的图，也不是全屏的，都是小块图，尺寸最大的那张没出问题

**Comment by xland** [comment]
@ajeyone 
图片上传的逻辑我改了一下，以应对平台服务偶发异常的问题，这几天就会发新版本，
敬请期待

**Comment by xland** [comment]
已发布新版本，请升级~

**Comment by ajeyone** [comment]
升级后打开，只剩标题了。。。
![image](https://user-images.githubusercontent.com/3040492/54087030-134ef400-438a-11e9-95f2-0f0de8c00a6d.png)

**Comment by xland** [comment]
@ajeyone 关了这个tab页重新打开一下

**Comment by ajeyone** [comment]
提示我什么格式不正确，确定之后就好了，今天再试试

**Comment by xland** [comment]
@ajeyone 

是增加了新的markdown编辑器导致的这个问题；
我今天早上又发了一个版本，
解决你刚刚说的“升级后只显示标题，不显示正文的问题”
