### ISSUE TITLE
分享到CSDN平台，如果默认是markdown编辑器，弹出窗口无法关闭

### ISSUE THREAD

**Issue by TommyMerlin** [xland/xiangxuema#24]
![image](https://user-images.githubusercontent.com/32566324/54103847-de35b680-4408-11e9-8a97-6da4a51130c8.png)

打开分享界面后为什么关不掉了。

**Comment by xland** [comment]
@TommyMerlin 

目前还不支持CSDN的markdown编辑器；
你可以在“想学吗”软件中，用软件自带的markdown编辑器编辑文章，
然后发布到CSDN（注意，CSDN默认编辑器不能是markdown编辑器）

谢谢你。
稍后我会针对CSDN做个提示，并解决掉这个无法关闭窗口的问题

**Comment by TommyMerlin** [comment]
OK 👍

**Comment by xland** [comment]
该问题已解决掉，请升级程序。
@TommyMerlin
