### ISSUE TITLE
带我去按钮的功能有问题，路径中把用户名写死了

### ISSUE THREAD

**Issue by pickwillingyh** [xland/xiangxuema#3]
路径中把用户名写死了，需要根据登录的用户来拼接路径

**Comment by xland** [comment]
@pickwillingyh 
我看了一下代码，没这个问题呀，能具体指出哪里存在这个问题吗？

**Comment by pickwillingyh** [comment]
cnblogs.vue文件66行

**Comment by xland** [comment]
@pickwillingyh 
这个参数是动态获取的呀，看上去没毛病呀


                        var id = curUrl.getParamVal('postid');
                        self.article.cnblogsId = id;
                        self.$root.needSave.a = true;
                        self.$root.needSave.c = true;
                        self.$root.save();
                        self.$parent.$parent.showSites = false;
                        self.$parent.publishText = "博客园：发布成功！";
                        swal({
                            icon: "success",
                            text: "博客园：知识发布成功,现在查看？",
                            buttons: [
                                '取消', "带我去"
                            ]
                        }).then((value) => {
                            if (!value) return;
                            var url = 'https://www.cnblogs.com/liulun/p/' + id + '.html';
                            window.nw.Shell.openExternal(url);
                        });
                        return;

**Comment by pickwillingyh** [comment]
https://www.cnblogs.com/liulun/pliulun这个应该是博客园的用户名，每个人的用户名都不一样的

**Comment by xland** [comment]
@pickwillingyh 
昏头了！居然没看到这里！等我到酒店后就改！

**Comment by pickwillingyh** [comment]
看到这了，但可惜我不会改，就给你提bug了

**Comment by xland** [comment]
已修复，谢谢
