### ISSUE TITLE
Mac 版的下载链接失效了

### ISSUE THREAD

**Issue by ajeyone** [xland/xiangxuema#31]

**Comment by ajeyone** [comment]
启动的时候崩溃，想更新一下，发现下载链接不行了

**Comment by xland** [comment]
@ajeyone ，抱歉，版本更新后readme没有及时更新，现在已经贴上了正确的链接地址了。

http://xiangxuema.com/download/%E6%83%B3%E5%AD%A6%E5%90%97-6.2.12.dmg

**Comment by ajeyone** [comment]
![image](https://user-images.githubusercontent.com/3040492/54655167-d3aba900-4afb-11e9-8f8c-67dba02b8c35.png)

**Comment by xland** [comment]
@ajeyone 我马上看看

**Comment by xland** [comment]
@ajeyone ,是上个版本证书打错了，现在已经修复了，请下载最新的版本

http://xiangxuema.com/download/%E6%83%B3%E5%AD%A6%E5%90%97-6.2.13.dmg

**Comment by ajeyone** [comment]
OK了
