### ISSUE TITLE
应用强退，TAB页名称未保存

### ISSUE THREAD

**Issue by ajeyone** [xland/xiangxuema#32]
上传不了图……

**Comment by xland** [comment]
@ajeyone 可能是因为版本更新的时候没有及时保存文章的缘故。

**Comment by ajeyone** [comment]
找到个复现步骤：
1.新建一个文章
2.填上标题，⌘+S（这个有用么？）
3.用系统的强制退出杀掉程序
4.再打开程序
5.标题栏没有标题了

**Comment by xland** [comment]
@ajeyone 
谢谢，下个版本解决这个问题

cmd+s有用的

**Comment by xland** [comment]
新版本已解决这个问题
