### ISSUE TITLE
点击“添加知识”无响应

### ISSUE THREAD

**Issue by 97CBR** [xland/xiangxuema#37]
点击 “添加知识” 后没有反应，点击之前已经创建好的文章知识，不显示内容且不可编辑。

**Comment by xland** [comment]
@97CBR ,什么操作系统，什么版本？是刚刚升级后出现的问题吗？是从什么版本升级到什么版本的？默认编辑器是什么编辑器？

**Comment by 97CBR** [comment]
WIN10,1803版本，忘记从哪个版本升级上来的，不过那时候只有四五个平台可以发博客的。然后，升级到6.3.0后，就无法点击编辑了。默认编辑器 HTML和MARKDOWN都无法勾选。卸载重装亦无法解决。

**Comment by xland** [comment]
@97CBR ，
很有可能是从很早的版本升级过来导致的问题（历次升级有一些特性不兼容很早的老版本）；

如果你数据不是很重要的话，
可以删一下本地数据目录就可以了：
C:\Users[name]\AppData\Roaming\xiangxuema\xxm

如果数据重要，需要手动改一下本地sqlite的表结构；
可以加我QQ412588801，我帮你改

**Comment by 97CBR** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi liulun
            问题已经解决，感谢您的支持。Marx
    
        
            
        
    
    
     
    
        
            
    
        
            
                
                    
                        
                    
                    
                        
                            marx
                            
                                    
                                    素米
                                  
                                     - 
                                    后端工程师
                            
                                
                                    13692506583
                                
                                
                                    824368602@qq.com
                                
                                
                                    
                                
                                
                                    
                                
                                
                                    
                                
                        
                    
                
            
        
    

        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年3月28日 18:28，liulun<notifications@github.com> 写道： 


@97CBR ，
很有可能是从很早的版本升级过来导致的问题（历次升级有一些特性不兼容很早的老版本）；
如果你数据不是很重要的话，
可以删一下本地数据目录就可以了：
C:\Users[name]\AppData\Roaming\xiangxuema\xxm
如果数据重要，需要手动改一下本地sqlite的表结构；
可以加我QQ412588801，我帮你改

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
