### ISSUE TITLE
标签字数限制太少，不够用

### ISSUE THREAD

**Issue by yidasanqian** [xland/xiangxuema#39]
如题

**Comment by xland** [comment]
@yidasanqian 
啥意思？是不是你标签写了太多字进去？

**Comment by yidasanqian** [comment]
> @yidasanqian
> 啥意思？是不是你标签写了太多字进去？

RuntimeException 这个很长吗

**Comment by xland** [comment]
我处理一下吧

**Comment by xland** [comment]
@yidasanqian 

最新版本已经不限制字数了
