### ISSUE TITLE
发布到博客园能不能支持先到草稿里面？

### ISSUE THREAD

**Issue by asxinyu** [xland/xiangxuema#4]
非常不错的工具，15年的老版本之前用了好多次。

现在这个版本发布是直接发布了，如果能支持发布到博客园的草稿箱就好了？

**Comment by xland** [comment]
我打算让用户自己点击发布按钮
我只是把文章标题和文章正文填到目标网站的页面里，然后把这个页面呈现给用户，
让用户自己点发布；
用户可以自由的保存草稿或发表

**Comment by xland** [comment]
已通支持
