### ISSUE TITLE
Mac下 复制粘贴不可用

### ISSUE THREAD

**Issue by cshlxm** [xland/xiangxuema#41]
Mac OS 10.13.6  下 复制和粘贴用不了，V6.3.1

**Comment by xland** [comment]
@cshlxm 
你的“想学吗”没有自动升级吗？
现在已经是6.3.3了
http://xiangxuema.com/download/%E6%83%B3%E5%AD%A6%E5%90%97-6.3.3.dmg，

你重启一下应用，等一会儿，看看有没有升级提示；
不行的话，就手动下载一下吧（上面的链接）
相信升级之后，就没这个问题了。

如果你能搞明白是什么导致你不能自动升级，麻烦你告诉我一下
