### ISSUE TITLE
分享到微信公众号有问题，提示『发生错误，请返回首页』，但是点击『首页』又没有反应

### ISSUE THREAD

**Issue by 552277** [xland/xiangxuema#42]

**Comment by 552277** [comment]
分享到微信公众号有问题，提示『发生错误，请返回首页』，但是点击『首页』又没有反应

**Comment by xland** [comment]
稍等，我试试！
@552277

**Comment by xland** [comment]
@552277 
在我这里（mac os），文章标题，文章内容（包括文章里的图片），都可以顺利的同步到微信公众号文章编辑页面；

你是在什么时候得到这个错误提示的，
你的操作系统是什么，
“想学吗”的版本号是多少？

**Comment by xland** [comment]
最新版本是6.3.5

**Comment by 552277** [comment]
> 最新版本是6.3.5

我这里显示的是6.3.6版本,操作系统是Mac 10.14.4.
提示错误时间：输入微信公众号账号和密码之后跳转时，弹出这个错误页面

**Comment by xland** [comment]
@552277 ,昨天发过新版本，现在最新的版本是6.3.6，方便加我QQ吗？412588801

**Comment by 552277** [comment]
您有微信吗，我可以加下您微信，我已经不用QQ好多年了

**Comment by xland** [comment]
@552277 我微信ID：liulun18158135758

**Comment by xland** [comment]
在多个账号下测试并没有复现这个问题，
征集愿意提供账号给我测试一下的人；

**Comment by xland** [comment]
又测了一个微信账号，
目前来看，这应该不是个问题，
暂时先把这个关掉吧，有问题再开~
