### ISSUE TITLE
HTML编辑器拖动改变图片大小，只能改变图片的宽，不能改变图片的高

### ISSUE THREAD

**Issue by Fourteenzju** [xland/xiangxuema#43]
希望可以任意尺寸调节图片大小，谢谢

**Comment by xland** [comment]
@Fourteenzju ，你用的是什么编辑器？

HTML编辑器是可以通过拖拽调整图片大小的呀~

**Comment by Fourteenzju** [comment]
![12](https://user-images.githubusercontent.com/31785358/56341187-d24aca80-61e6-11e9-8172-9a2357f120a7.gif)
只能左右调整，不能上下调整

**Comment by xland** [comment]
咦，你是怎么搞成这样了？

你看看我readme里的第三个图片
https://camo.githubusercontent.com/c71ef55fbca216b2f651b4c32d17a6c2696fde8e/687474703a2f2f7777772e7869616e677875656d612e636f6d2f646f632f7075626c6973682e676966

**Comment by Fourteenzju** [comment]
不行，不能放大更多了，不能无限放大，麻烦你试试

**Comment by xland** [comment]
@Fourteenzju ，试过，确实有这个问题，我尝试处理一下！

**Comment by xland** [comment]
这个问题在新版本中已经解决了
@Fourteenzju 

请升级到新版本
