### ISSUE TITLE
关于标签个数限制、文章内添加标签便利性的一些建议

### ISSUE THREAD

**Issue by Fourteenzju** [xland/xiangxuema#44]
1、希望能取消单个知识标签数6个的限制
2、希望可以有专门只添加、删除和修改标签的功能，比如直接在标签面板上操作
3、在编辑知识的时候可以调用标签面板，这样就只需要点击添加标签就可以了
感谢，期待回复~

**Comment by xland** [comment]
@Fourteenzju ,非常感谢你的建议，
其中第三点我已经在开始考虑怎么改了；
其他两点容我思考思考再说；

抱歉这么晚给你回复~
（一般不会这么晚回复的，这两天刚好有点事...）

**Comment by Fourteenzju** [comment]
辛苦了

**Comment by xland** [comment]
@Fourteenzju 

这个问题已经解决了，请升级版本，再次感谢你的建议~
