### ISSUE TITLE
博客预览区域内容显示不全

### ISSUE THREAD

**Issue by octopusy** [xland/xiangxuema#45]
你好，最近使用想学吗客户端，发现当博客内容过长的话，预览区显示的内容会显示不全，这个可以修复下吗？

**Comment by xland** [comment]
@octopusy ,是不是markdown编辑器？能截个图片给我看看吗？

**Comment by octopusy** [comment]
![image](https://user-images.githubusercontent.com/8248053/57421990-c62fb700-7240-11e9-8e31-58eb81aabee9.png)

**Comment by xland** [comment]
@octopusy 
你的意思是两侧滚动条同步情况不一致，对不对？

**Comment by octopusy** [comment]
不是，右边预览区已经滚动到底了，内容没加载完

**Comment by xland** [comment]
@octopusy 

懂了！谢谢反馈，我手头上的事情完了就处理这个问题！

**Comment by xland** [comment]
新版本已解决此问题
@octopusy
