### ISSUE TITLE
感觉不太友好呢

### ISSUE THREAD

**Issue by RyanLee0129** [xland/xiangxuema#46]
界面颜色感觉怪怪的，不鲜明。默认窗口有点太小了

**Comment by xland** [comment]
@RyanLee0129 

你是windows操作系统吧，程序在windows下确实有点小，尤其是大屏幕的电脑；
这个我后面会改改；

颜色对比太明显的话，不适合长期使用呢，太扎眼

**Comment by RyanLee0129** [comment]
对，是windows，1920*1080。Mac分辨率不是更高嘛。

**Comment by xland** [comment]
@RyanLee0129 
这个问题在我本地开发环境已经搞定，请静待发版

**Comment by xland** [comment]
新版本已发布，此问题已解决
