### ISSUE TITLE
希望尽快支持csdn 的markdown编辑器

### ISSUE THREAD

**Issue by Alexios-cd** [xland/xiangxuema#48]

**Comment by xland** [comment]
@fwj1991 

“想学吗”是支持markdown编辑器的，
你可以把你CSDN的默认编辑器设置成HTML编辑器
然后用“想学吗”的markdown编辑器编写文章，
这样就可以把文章顺利的提交到CSDN了

**Comment by Alexios-cd** [comment]
但是这样的话提交上去的其实是html格式的文章，以后想大量调整的话没有markdown方便。希望支持远程的markdown,提交上去的是markdown,csdn上点击编辑的时候，可以直接编辑修改原版的markdown文件，这个一般情况下，程序员超级需要……

**Comment by xland** [comment]
嗯~我考虑一下~

**Comment by Alexios-cd** [comment]
IT工作者需要纯MarkDown格式，大恩不言谢
