### ISSUE TITLE
发现在 源码格式下无法保存修改

### ISSUE THREAD

**Issue by 520Girl** [xland/xiangxuema#49]
比如我在 源码格式下换行，并ctrl+s 之后切换到 编辑模式下 看见依然没有换行，
有的bootstrap 标签无法添加(在源码格式下) 比如abbr  而address 标签又可以添加

**Comment by 520Girl** [comment]
希望 能 修改一下 能达到完美就好了

**Comment by xland** [comment]
嗯！这一点确实可能没做到，为什么把这个issue关了？应该是个问题呀

**Comment by xland** [comment]
新版本已解决此问题
