### ISSUE TITLE
博客园图片上传时，好慢，怀疑是卡死了？

### ISSUE THREAD

**Issue by pickwillingyh** [xland/xiangxuema#5]
猜测可能和问题3的原因相同，用户名不对。
在浏览器中打开博客园，发现，文章并未上传。

**Comment by xland** [comment]
再试试看，问题3已经修复了
@pickwillingyh

**Comment by pickwillingyh** [comment]
试用了最新版，发现win8.1上打开后白屏了，什么了也没有了。

**Comment by xland** [comment]
@pickwillingyh 
这个问题和 #7 看起来是一样的
我改了相关的代码，
可以再试试看
谢谢！

Duplicate of #7

**Comment by xland** [comment]
这个问题已经在6.0.9中修复
