### ISSUE TITLE
启动程序窗口大小设置为上次窗口关闭时的大小（兼容窗口最大化）

### ISSUE THREAD

**Issue by tianxia0079** [xland/xiangxuema#57]
现在打开窗口是小窗口，希望可以默认最大化现实

**Comment by xland** [comment]
@tianxia0079 

你觉得是做成“记住上次打开窗口的尺寸”好？
还是做到配置里，供用户设置好？

**Comment by tianxia0079** [comment]
> @tianxia0079
> 
> 你觉得是做成“记住上次打开窗口的尺寸”好？
> 还是做到配置里，供用户设置好？

我觉得，记住上一次就可以了，我最大化或者改变窗口大小的结果就是我想设置的，记住就行

**Comment by xland** [comment]
好，下个版本会提供这个功能

**Comment by tianxia0079** [comment]
@xland 今天升级新版本，看更新日志说窗口自动记忆大小，可是没生效哦！是不是缓存啥的没处理好！要不再更新个版本0.0

**Comment by xland** [comment]
@tianxia0079 你是什么操作系统？？

**Comment by xland** [comment]
windows版本已经有这个特性了

**Comment by tianxia0079** [comment]
大佬我用的win10 版本号 1903
我是远程桌面访问的，本地访问还没试过，难道远程桌面原因？

**Comment by xland** [comment]
@tianxia0079 我这里都是好的呀，
win版本
6.4.8
6.4.9
都支持记住上次关闭时窗口的大小（包括最大化）

**Comment by tianxia0079** [comment]
@xland 升级最新版本已经好了。
发布到某个自媒体平台时候的窗口，也可以支持一下记忆功能吗
现在还是小窗口

**Comment by xland** [comment]
@tianxia0079 
确实，应该做一下~谢谢建议！

**Comment by xland** [comment]
发布窗口大小记忆的问题，我后面会做，这个issue先关掉了
