### ISSUE TITLE
向微信发不出去

### ISSUE THREAD

**Issue by zitup** [xland/xiangxuema#58]
你用的什么操作系统：
          macos
你用的什么版本的“想学吗”：
        6.4.8

向微信公众号发，本地只能用HTML编辑器吗？没找到微信编辑器可以设置成html格式

**Comment by xland** [comment]
@zytjs 
微信公众号平台只有HTML编辑器，不需要额外的设置；
你在“想学吗”里用的是什么编辑器

**Comment by zitup** [comment]
@xland 本地用的md，一种浮层提示提交中，如果使用html编辑器可以马上转换掉

**Comment by xland** [comment]
@zytjs windows版已经更新，请再试一下

**Comment by zitup** [comment]
@zytjs 我是mac😂  
另外，网上有编辑器把md转换为微信格式的，我一般都用那个再转一下，再发

**Comment by xland** [comment]
@zytjs 

mac版本已更新，你升级一下看看
win版本已经确认过没问题了；

你说的md转微信格式，我不太清楚，对咱们这个软件有什么帮助吗？

**Comment by zitup** [comment]
@xland 
![image](https://user-images.githubusercontent.com/12710516/63735223-ae447780-c8b1-11e9-8c68-8ba48bd96192.png)
有一篇md可以转，但代码格式有问题，有一篇但转化一直上面那样

**Comment by xland** [comment]
是特定某篇文章提交不上去吗？
还是所有文章提交不上去？

加我QQ412588801，把文章正文发我，我试试看，哪里有问题

**Comment by zitup** [comment]
@xland OK

**Comment by zitup** [comment]
@xland 老哥你没通过好友

**Comment by xland** [comment]
@zytjs 

已确认是文章正文内有错误地址的图片导致的，这个issue先关掉了
