### ISSUE TITLE
怎么用啊 新增一个测试的文章 然后 账号也登录了 没有自动上传哈

### ISSUE THREAD

**Issue by 931743010** [xland/xiangxuema#6]
![image](https://user-images.githubusercontent.com/9315727/53213489-1a84bb00-3684-11e9-93cf-c36c7e129a78.png)
mac简书 一直提示 这个  我选择了 没用

开源中国一直在刷新
知乎进去 没任何反应哈

还有客户端的源码怎么不开源啊  不能自己进行调试然后提交bug fix了

**Comment by xland** [comment]
什么操作系统？
我就是在这个源码下做的这个软件，源码都提交了的
@931743010

**Comment by 931743010** [comment]
>什么操作系统？ ...

@xland mac系统上面的

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xland** [comment]
@931743010 

我已经处理掉这简书、开源中国、知乎的问题了
你再次打开程序，应该提示你更新，帮忙确认一下吧，谢谢。

**Comment by 931743010** [comment]
上面几个问题都已经解决

**Comment by realyrare** [comment]
我也是遇到同样问题，软件更新了好几次，打开其他平台没见得自动上传上去，莫非全部复制粘贴过去。win10系统

**Comment by xland** [comment]
@mhg215 

请看一下软件右下角的版本号是不是6.2.14，加我QQ：412588801
