### ISSUE TITLE
百家号在哪设置默认编辑模式为html啊

### ISSUE THREAD

**Issue by tianxia0079** [xland/xiangxuema#62]
你用的什么操作系统：
          windows,linux,macos三选一
你用的什么版本的“想学吗”：
        （软件右下角看版本号）

**Comment by xland** [comment]
@tianxia0079 ，百家号只有HTML编辑器，不用额外设置；

你文章提交不到百家号吗？

**Comment by xland** [comment]
@tianxia0079 
百家号的问题已修复，请更新为最新版本
