### ISSUE TITLE
win7,win8 应用打开白屏

### ISSUE THREAD

**Issue by Phamay** [xland/xiangxuema#7]
安装后第一次自动打开正常，关闭后再打开就是白板了，卸载重新下载安装还是这样

**Comment by xland** [comment]
@Phamay 

什么操作系统下的问题呀？

**Comment by Phamay** [comment]
win7 x64企业版的哦

**Comment by xland** [comment]
@Phamay ，我并没有真正的重现你说的BUG，
但我确实改了可能会造成这个问题的相关代码，
你可以升级新版本，再试试看

**Comment by xland** [comment]
这个问题已经在6.0.9中修复

**Comment by pickwillingyh** [comment]
你好，我试用了6.0.10版本，win8.1 x64, 还是白屏。
并且，点击关闭窗口的按钮，没有反应。

**Comment by xland** [comment]
起床之后我就去看

**Comment by xland** [comment]
我在win10下试过没问题，
方便帮忙调试一下吗？我QQ：412588801
@pickwillingyh

**Comment by Phamay** [comment]
确实，更新后打开白板，关闭按钮无效，只能任务管理器结束

**Comment by xland** [comment]
@Phamay @pickwillingyh 

方便加一下我QQ，辅助我远程调试一下吗？

**Comment by Phamay** [comment]
我是在公司使用，所以没法远程调试呢

**Comment by pickwillingyh** [comment]
QQ搜索不到呢发自我的-------- 原始邮件 --------主题：Re: [xland/xiangxuema] win7,win8 应用打开白屏 (#7)发件人：liulun 收件人：xland/xiangxuema 抄送：x12m21x ,Mention 我在win10下试过没问题，

方便帮忙调试一下吗？我QQ：412588801

@pickwillingyh

**Comment by xland** [comment]
咦，我QQ天天在线，这两天还有一个人加我来着
@pickwillingyh

**Comment by pickwillingyh** [comment]
刚添加了，你确认下

**Comment by xland** [comment]
新版本在WIN8下已验证，没有问题了，暂时关掉此issue
