### ISSUE TITLE
生成表格的html 复制到markdown

### ISSUE THREAD

**Issue by Layty** [xland/xiangxuema#8]
生成表格的html 复制到markdown 显示中有很多空行

**Comment by xland** [comment]
@Layty ，我先处理紧急的问题，一有空我就看你这个问题

**Comment by xland** [comment]
#11

**Comment by xland** [comment]
已支持markdown，请升级新版本

**Comment by Layty** [comment]
[可能你没理解我的意思,我本意是在你的html的编辑器中,输入一个表格(表格中有多行文字),然后复制他的html到markdown中,markdown中的渲染就不太好了,空行会很多导致新表格(在md)中,如下图所示
[![A9haLt.png](https://s2.ax1x.com/2019/03/11/A9haLt.png)](https://imgchr.com/i/A9haLt)

**Comment by xland** [comment]
确实理解错了你的意思，抱歉。

可是咱们的应用现在已经支持markdown了，
你直接用应用中的markdown编辑器编辑md内容不好吗？
这样就不必用那个html的编辑器了

（应用右下角左侧setting里，可以设置默认编辑器）

**Comment by Layty** [comment]
markdown 里面嵌入一些合并单元格和换行 这个时候还是html嵌入比较好

**Comment by xland** [comment]
@Layty ，嗯确实是这样，我想想办法简化一下html编辑器里生成的table

**Comment by Layty** [comment]
我找了很多在线编辑表格的,都和你的一样,只有这个生成的很完美
https://ckeditor.com/ckeditor-4/demo/#document

**Comment by xland** [comment]
嗯！ckeditor确实不错呢！

**Comment by Layty** [comment]
而且支持excel直接复制进去 然后复制到md
但是那个demo不支持直接复制html  我也不懂这个前端的编程,只能使用 省察元素复制,相当麻烦

**Comment by xland** [comment]
@Layty 
我已经把编辑器改成ckeditor了！
请下载最新版本，有什么问题随时联系我！

**Comment by Layty** [comment]
嗯嗯 完美支持excel了，（支持复制回excel编辑后再复制回去）
再说一个小众的问题 
就是如果自己输入表格的话，如果同一个单元格换行的话显示是有问题的
问题在于
```
<table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<tbody>
		<tr>
			<td>123</td>
			<td>222</td>
		</tr>
		<tr>
			<td colspan="2">111222<br />
			555<br />
			666<br />
			888<br />
			999</td>
		</tr>
		<tr>
			<td>222</td>
			<td>111</td>
		</tr>
	</tbody>
</table>
```
中间的
```
			555<br />
			666<br />
			888<br />
			999</td>
```
需要变更为
```
 <td colspan="2">111222<br /> 555<br /> 666<br /> 888<br /> 999</td> 
```
也就是消除中间的换行，才能很好的显示

**Comment by Layty** [comment]
这个应该是markdown 解析的问题了，应该和你这个没关系，请忽略上述问题
<table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<tbody>
		<tr>
			<td>123</td>
			<td>222</td>
		</tr>
		<tr>
			<td colspan="2">111222<br />
			555<br />
			666<br />
			888<br />
			999</td>
		</tr>
		<tr>
			<td>222</td>
			<td>111</td>
		</tr>
	</tbody>
</table>__

**Comment by xland** [comment]
哈哈！好的！
