### ISSUE TITLE
更新完，之前的文章没了

### ISSUE THREAD

**Issue by nian8** [xland/xiangxuema#9]

**Comment by xland** [comment]
@nian8 
你是什么系统？

文章数据和程序代码保存在不同的目录；
windows 下文章数据在：C:\Users\[your name]\AppData\Roaming\xiangxuema\xxm
你手动清理过相关路径吗？

**Comment by lfzm** [comment]
可以进行远程保存吗？或者通过Github创建库进行存储

**Comment by xland** [comment]
@AClumsy 
目前还未对接github呢。后续我会建云服务，允许大家把自己的文章保存在云端

**Comment by nian8** [comment]
win 上，原安装版本6.0.4，安装目录program files；
更新版本为6.0.8，自动安装，未重新选择路径，安装路径在C:\Users\${name}\AppData\Local\Programs\xiangxuema\想学吗.exe

帮忙看下！

**Comment by ghost** [comment]
mac也是

**Comment by ghost** [comment]
mac也是

**Comment by xland** [comment]
@mufengcoding @nian8 

我在MAC和Win下试了从6.0.8升级到6.0.9；
没发现文章数据丢失的问题呀（我本地没存6.0.4了-_-!）

我想问一下：
如果退回6.0.4你文章还在吗？
升级到6.0.9后，写一篇文章，再重装一下6.0.9文章还在吗？

给您造成的不便，深表愧疚！
有任何问题，可以QQ联系我：412588801
